### ISSUE TITLE
Is this a core issue ?

### ISSUE THREAD

**Issue by tenkoshimu** [renzuzu/renzu_multicharacter#15]
awesome work on the multi and spawn i'm a big fan, 
got a lil issue do you know what this could be ?

![screen2](https://user-images.githubusercontent.com/101616320/205421417-cf7484c1-e0c4-4b59-a099-416569e657b0.png)

**Comment by renzuzu** [comment]
this resource is only tested on the latest Qbcore right now..

did you modify your player.lua from qbcore?

the line 30: player.lua confirms that the New variable is not nil or false.

the line 30: from player.lua of qbcore registered the new data to the slot.
it fails to line:145 of player.lua of qbcore.

in my version this is jobs data.
but i never encounter this on my qbcore version.
