### ISSUE TITLE
UI bug?

### ISSUE THREAD

**Issue by b1naryerr0r** [renzuzu/renzu_multicharacter#16]
Hi renzu!, love your work :3 
some players are having this problem
![image](https://user-images.githubusercontent.com/68873710/205445387-49311597-0c62-436c-9dd3-101ec16e4185.png)
you know why?

**Comment by renzuzu** [comment]
sometimes when do /relog
ill try to reproduce this and try to hide while relogin.

**Comment by b1naryerr0r** [comment]
is there a solution?, or something? :c

**Comment by b1naryerr0r** [comment]
![image](https://user-images.githubusercontent.com/68873710/205448247-c21c7f39-a099-43fc-be79-cfe1766c2137.png)
I have relog in false

**Comment by b1naryerr0r** [comment]
I tried something, i put qb-multicharacter custom and the user can create a character, when i put again your creator it loads fine the character and shows the UI correctly.
It appears to be the character creation when the user doesn't have a character created

**Comment by renzuzu** [comment]
thank i will try this repro.

also i have updated the server thing ..

**Comment by renzuzu** [comment]
i have tried your repro steps..

![image](https://user-images.githubusercontent.com/82306584/205449766-c4904e45-b392-46d3-91ed-c01e26a3a865.png)

can you retry in test server and use the latest version
delete all your characters to test

**Comment by b1naryerr0r** [comment]
I tested it but it shows like this
![image](https://user-images.githubusercontent.com/68873710/205450880-eff143dd-fbd4-4325-8968-0cec90544993.png)
can you send me your config file for qbcore?, just for compare with what i edit it's correct or not

**Comment by renzuzu** [comment]
is there no server error?

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_multicharacter/commit/ea525e99002c8d1286053b185cf258975b9e9a42

i have tweak the client to prevent empty datas to slots and characters.

appreciate if you test the latest version.

and also tell me your FXversion , game build version

**Comment by b1naryerr0r** [comment]
Hi renzu!, i tested it and it shows like this
![image](https://user-images.githubusercontent.com/68873710/205497246-77e88cb2-5d53-42e3-b942-169b4b51f963.png)

When i press "create" gives me this error and won't happen anything
![image](https://user-images.githubusercontent.com/68873710/205497141-e55d1c35-a412-4808-873e-f7b135dfa6d3.png)
![image](https://user-images.githubusercontent.com/68873710/205497262-f279afd7-a314-47f6-ad1e-cde410fce634.png)

**Comment by renzuzu** [comment]
what it shows you is correct, based on whats you set on config.

you did set Config.UseDefaultRegister, which wont use the default registerration.

and you set 

Config.RegisterHook = {
event = false,
call = 'esx_identity:showRegisterIdentity' -- sample esx_identity compatibility. for more compatibilty see bottom.
}

event = false means it should use export.

call = '' -- this is the event name or exports link.


if you want to use esx_identity
set the event to true.

**Comment by b1naryerr0r** [comment]
Hi renzu!, i tried but keeps me doing the same, I came to the conclusion that the menu has this error when the player does not have any created character, it only happens in the first creation

**Comment by renzuzu** [comment]
which issue?
you posted 2 issues in this single thread.

is this about the first issue or your 2nd issue which you upload 2 picture.

if this is about first issue, i need more reproduction steps.

if this is about 2nd issue.

make sure you are really using esx_identity
because in default its esx_identity event is included in the config.

**Comment by renzuzu** [comment]
you can pass me your discord so i can help you faster

**Comment by b1naryerr0r** [comment]
yes!, here you have my disc! Knox#3719

**Comment by renzuzu** [comment]
what framework do you use?
