### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_multicharacter#17]
i think bug yung map sa bottom left lumalabas agad sya before naman hindi
![image](https://user-images.githubusercontent.com/105653892/205447972-768ddbdf-1ca3-4e90-9741-a4222ed8f213.png)

**Comment by renzuzu** [comment]
not a bug , i  have removed this

**Comment by raaazeee** [comment]
ganon padin, 
![image](https://user-images.githubusercontent.com/105653892/205453992-8edbd2bc-07dd-4e90-9f81-8ad87fedd076.png)

**Comment by renzuzu** [comment]
i said i aalready removed the feature to interfere with radar
its mean it will show up

because when i do others will have issue radar is on, or radar is off when spawning
