### ISSUE TITLE
Creating character camera

### ISSUE THREAD

**Issue by soymaxi** [renzuzu/renzu_multicharacter#18]
How can i change the heading for the camera when i creating my character?

**Comment by renzuzu** [comment]
whats your purpose on this?

the camera setting by default is configure from the spawn locations of ea character.

you can try editing this

![image](https://user-images.githubusercontent.com/82306584/205456839-eac096b5-aba4-45f7-b18f-a3e1fef8983d.png)

the setcamparams is the main cam
pointcamtocoord is the coordinates of ped.
