### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mistr140** [renzuzu/renzu_multicharacter#19]
If you use your multicharactes you status will stop working and save data I send config 
![obrazek](https://user-images.githubusercontent.com/43046423/205993903-7193f439-5c12-496e-9510-6336e84a1858.png)

**Comment by renzuzu** [comment]
you dont need to put that thing anymore.. its for lower esx only

**Comment by renzuzu** [comment]
unfortunately the renzu_status is outdated..

you could share the same status on every character.


i will try to update the status to use logout events

**Comment by mistr140** [comment]
> unfortunately the renzu_status is outdated..
> 
> you could share the same status on every character.
> 
> i will try to update the status to use logout events

I tried to edit the status, but I can't wait for the character to be selected, I didn't figure it out. But if it were possible, it would be enough to use xPlayer.identifier
