### ISSUE TITLE
Players in "different universes"

### ISSUE THREAD

**Issue by Waidiation** [renzuzu/renzu_multicharacter#21]
I dont really know how to explain it, but basically players spawn in their own universe sometimes.. where they dont see anyone else.. and even the coordinates are undetectable.. any idea what would cause this.. I remember this being something that happened when using the logout function in qb-multicharacter.. but its doing it pretty consistnatly without even reloggin..

Using QB-Core btw

**Comment by renzuzu** [comment]
when player choose characters
![image](https://user-images.githubusercontent.com/82306584/206338066-cae9135f-55d3-4abc-a1c3-da0e3d6a5f98.png)

routing bucket is always set to 0
which is default?
what are you default worlds?

and i seen some cases reported in cfx forumes , if players is around 500-800 it could happen as it seems a network entity limit on the same grid

**Comment by Waidiation** [comment]
We have not changed the default world so it should be 0.. Hmm

**Comment by renzuzu** [comment]
you could remove the setplayerroutingbucket in server.

but this will make the selecting / creating characters are visible in the other players

**Comment by Waidiation** [comment]
> you could remove the setplayerroutingbucket in server.
> 
> but this will make the selecting / creating characters are visible in the other players

This is still happening even with Bucket commented out.. hmm this is weird
