### ISSUE TITLE
BG MUSIC seems to not work.

### ISSUE THREAD

**Issue by xmidnite** [renzuzu/renzu_multicharacter#26]
I have set the 

Config.bgmusic = true 

but there were no music while multicharacter is loading. 

also encountered this error. I wan't to know what steps could I do to fix this :) 
![image](https://user-images.githubusercontent.com/34018452/208830632-75d6fb0f-6299-4568-88aa-8a7061707b4c.png)

-Using QBCore and fivemappearance

P.S. I'm new to doing script and still learning. Thanks!

**Comment by Kathou99** [comment]
Hi on the ESX I have the same issue :) I don't need it so I did not look into this :)

**Comment by renzuzu** [comment]
its known bug when using xSound.
current works on my forked
renzu_mp3
