### ISSUE TITLE
Dead Player

### ISSUE THREAD

**Issue by galibmahin** [renzuzu/renzu_multicharacter#28]
Player comes out dead sometime when they join the server.

**Comment by blk07shelbygt** [comment]
Same issue

**Comment by xmidnite** [comment]
got same issue  :(

**Comment by Sully1796376** [comment]
same issue

**Comment by jaylac2000** [comment]
same here

**Comment by DannyHD001** [comment]
having the same issue @renzuzu

**Comment by SwagDaddyBrad** [comment]
Same issue

**Comment by SwagDaddyBrad** [comment]
@renzuzu Love your scripts mate, any chance you know what is causing our issue?

**Comment by DannyHD001** [comment]
This seems to be cause something is putting you high up and you fall down. Hope renzu can figure it out.
