### ISSUE TITLE
VexCreator

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_multicharacter#3]
How can i trigger the VexCreator after i fillup the identity?

**Comment by renzuzu** [comment]
is your vexcreator is skinchanger?

replace this

![image](https://user-images.githubusercontent.com/82306584/204158543-7d7327b7-b907-4a46-84ef-d272ae015194.png)

note this screenshot is from latest

**Comment by hasidu** [comment]
is vexcreator will work with this because with esx leagacy multi character it doesn't worked

**Comment by hasidu** [comment]
this is the vexcreator https://forum.cfx.re/t/paid-vexcreator-a-skinchanger-made-it-by-vexdev/4633279

**Comment by renzuzu** [comment]
it should work. 

i just tried right now

![image](https://user-images.githubusercontent.com/82306584/204165835-f2b1212b-3603-4531-aa68-699e6b825d02.png)

since its uses skinchanger and esx_skin it should work.

if you have issues implenting it, let me know ill assist you

**Comment by renzuzu** [comment]
i think your issue is the camera stuck.
i will remove this logic. its the same with esx multicharacter.

since this vexcreator does not return callbacks.

**Comment by renzuzu** [comment]
this commit https://github.com/renzuzu/renzu_multicharacter/commit/54577d829b542f039e82a159f76f78f3fb378cb7

can easily manage creator events or exports

you just need to insert the correct event

**Comment by razeraze** [comment]
thanks tito renz

**Comment by hasidu** [comment]
ok thank you renzuu for your help and for your work 

so now if we put the vex creator it will work withouth any problems right ?

no camera stuck after you spwan the character right ?

**Comment by hasidu** [comment]
Also is there way that we can use our identy system ?

**Comment by renzuzu** [comment]
custom identity is now supported.
but if your identity is not using esx_identity logic. you need to modify more. look for config for info.

> Also is there way that we can use our identy system ?

**Comment by hasidu** [comment]
Its ok I will use your one

**Comment by hasidu** [comment]
> custom identity is now supported. but if your identity is not using esx_identity logic. you need to modify more. look for config for info.
> 
> > Also is there way that we can use our identy system ?

hi renzu i am using rody identity is this multicharacter will work with that ?

**Comment by renzuzu** [comment]
i havent tried it yet, is it open source?

**Comment by hasidu** [comment]
Yes its opensource
