### ISSUE TITLE
using the new illenium-appearance

### ISSUE THREAD

**Issue by parham-ebrahim** [renzuzu/renzu_multicharacter#31]
the new illenium-appearance (fivem-appearance update) does not work with this. i've tried lookin for the functions. and rewrite the callbacks. but on making new character, the menu doesn't show up.

**Comment by DannyHD001** [comment]
Hi, got most working but not able to make new characters. Hope to gear from ranzuzu on this.

**Comment by DannyHD001** [comment]
Saw the new update, but still only getting 1 charslot. I had 3 and delted 2 but can not make new

**Comment by Bama94** [comment]
Same here on QBCORE. Upon creating a new character, it just has you spawn then no clothing menu pops up
