### ISSUE TITLE
Creating first Character showing spawn first

### ISSUE THREAD

**Issue by DannyHD001** [renzuzu/renzu_multicharacter#35]
Hi
When creating a new character I get moved to spawn selector and not the default place for creating a new char. 
This is when using qb-core, I am also using your spawn selector.
Am I doing something wrong or what do you think.

**Comment by renzuzu** [comment]
dont autospawned spawnmanager

**Comment by DannyHD001** [comment]
> dont autospawned spawnmanager

Not sure what you mean about that.
