### ISSUE TITLE
Cant Create Chaw

### ISSUE THREAD

**Issue by ismail771** [renzuzu/renzu_multicharacter#39]
Config:```
## These resources will start by default.
ensure oxmysql
start default
ensure es_extended
start ox_lib
start illenium-appearance
ensure multichar
```

Error:

[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface
[    script:multichar] Loading Data for twoface

**Comment by renzuzu** [comment]
you should show what error.

**Comment by ismail771** [comment]
> you should show what error.

Thats not really an error what i get, i know where it coming from but dont know how to fix. Is coming from GetPlayerId

**Comment by renzuzu** [comment]
is there any assets like vehicles ,eups loaded after the list of resource you mention?

because this is ESX or the sql is timing out so the getplayerid not returning data at all.

**Comment by ismail771** [comment]
> is there any assets like vehicles ,eups loaded after the list of resource you mention?
> 
> because this is ESX or the sql is timing out so the getplayerid not returning data at all.
Only those who i mentioned like that its started

**Comment by renzuzu** [comment]
you should load all big assets  before the es extended and other resources

**Comment by renzuzu** [comment]
big assets i mean the vehicles, eup folders
