### ISSUE TITLE
FiveM - Appearance

### ISSUE THREAD

**Issue by SiahRBLX** [renzuzu/renzu_multicharacter#40]
FiveM - Appearance with multicharacter not working

**Comment by SiahRBLX** [comment]
https://imgur.com/a/cTSdcCt

**Comment by renzuzu** [comment]
did you use the release version of fivem-appearance?

**Comment by SiahRBLX** [comment]
Yes, the issue is i have restart the script after server fully loaded to u to load in with multicharacter

**Comment by renzuzu** [comment]
does your fivemappearance folder name like this `fivem-appearance`

**Comment by SiahRBLX** [comment]
Yep - https://imgur.com/a/h2POkxN

**Comment by SiahRBLX** [comment]
fiveM - appearance does start when I check the logs but some reason your script gives that error so I have to restart fivem-appearance then renzu_multicharacter

**Comment by SiahRBLX** [comment]
Fixed this issue

Had to load fivem-appearance before renzu_multicharacter

**Comment by renzuzu** [comment]
thats correct

**Comment by Womack-Mac** [comment]
I did this but it still doesn't fix my issue
