### ISSUE TITLE
Creating new character bug

### ISSUE THREAD

**Issue by Jcw223** [renzuzu/renzu_multicharacter#41]
whenever somebody tries to create a new character once they get to the registration page to fill in the information the game crashes with this error... (Game crashed: GTA5_b2372.exe!sub_140744A10 (0x146b))

**Comment by renzuzu** [comment]
i need more information.

Client Version. aka Canary, release.
Framework: ?

**Comment by Jcw223** [comment]
Never mind. Issue seemed to resolve itself. Am using qbcore though. Using canary and config is default other than to set up for qb.
