### ISSUE TITLE
Player Invisible

### ISSUE THREAD

**Issue by tday130** [renzuzu/renzu_multicharacter#44]
I am using fivemappearance and my players are invisible when loading in and sometimes when spawning in its invisible unless I open clothing menu with admin menu and select a ped. And also the ped is invisible when a regular person is creating a character until they select which ped they are using in the clothing menu.

**Comment by tday130** [comment]
['fivemappearance'] = {}, -- is there any creator uses fivemappearance? i will leave this todo for now what do I put inside of the brackets for this?

**Comment by tday130** [comment]
I am supposed to launch my server by 9PM today and would like this multicharacter working correctly before I launch please help me lol

**Comment by renzuzu** [comment]
they only become invisible if they cancel the character creation.
unless some error throw in server when you save the character.

**Comment by tday130** [comment]
whats your discord?

**Comment by tday130** [comment]
Theres no error for character creation and theres nothing canceling it

**Comment by renzuzu** [comment]
leave your discord ill add you, i need to know what framework are you using

**Comment by tday130** [comment]
qbcore and Joey Thumper / Luke Hobbs#7402

**Comment by tday130** [comment]
what apartment script do you reccomend using with renzu multicharacter? qb apartments wasnt working with renzu spawn and now my devs are saying theres a error from our apartment script because of renzu multicharacter

**Comment by renzuzu** [comment]
your devs must do a custom export trigger to use the apartment script
or dont use renzu_spawn and use qb-spawn to able spawn in apartment without custom exports.

**Comment by tday130** [comment]
did you add me on discord? My characters are still invisible

**Comment by renzuzu** [comment]
Hobbs#7402

? added

**Comment by tday130** [comment]
The issues I have with renzu multicharacter 
[    133890] [b2612_GTAProce]        CrBrowserMain/ https://nui-img/pedmugshot_01/pedmugshot_01?1678834484113 (@renzu_multicharacter/web/script.js:49)
[    133953] [b2612_GTAProce]        CrBrowserMain/ https://nui-img/pedmugshot_02/pedmugshot_02?1678834484181 (@renzu_multicharacter/web/script.js:49)

& Invisible Peds on multicharacter screen please help me fix them

**Comment by renzuzu** [comment]
try the latest version now.

**Comment by tday130** [comment]
The new one I still have invisible characters.

**Comment by tday130** [comment]
Config.SkinMenus = {
	['skinchanger'] = {
		['esx_skin'] = {event = 'esx_skin:openSaveableMenu', use = false},
		['VexCreator'] = {event = 'VexCreator:loadCreator', use = false},
		['cui_character'] = {event = 'cui_character:open', use = false},
		['example_resource'] = {exports = 'exports.example:Creator', event = nil, use = false}, -- example support exports
	},
	['illeniumappearance'] = {}, -- is there any creator uses fivemappearance? i will leave this todo for now
	['fivemappearance'] = {}, -- is there any creator uses fivemappearance? i will leave this todo for now
	['qb-clothing'] = {
		['qb-clothing'] = { event = 'qb-clothing:client:openMenu', use = true},

**Comment by tday130** [comment]
What do I put for fivem appearance export? I need to know

**Comment by tday130** [comment]
***Okay wait invisible players are fixed. But my ped mugshot is still messing up I have 3 characters and only one of them has a mugshot.***

**Comment by renzuzu** [comment]
that is GTA thing, but most of the time its should not happen at all.

it can happen if you restart the resource multiple times.
