### ISSUE TITLE
DEFAULT SPAWN and BGMusic

### ISSUE THREAD

**Issue by human1104** [renzuzu/renzu_multicharacter#46]
Hello!

I tried to modify default spawn coordinate, top of a pier but the character is under the pier. The coordinates is correct, but the character is wrong place.  I tried to modify Y coordinate, but character dosnt moved. 

And i downloaded renzu MP3  too. Inside the game is working, i can play music. But in multicharacter intro is silence.  Downloaded XSound too, but also silence. 

And when i tried   rewrite this:
Config.cam = true to Config.cam = false   

do not changed nothing.

**Comment by renzuzu** [comment]
can you share to coordinates, this could be because of getting ground Z of current coordinates.

>But in multicharacter intro is silence
does the config.bgmusic is set to true?

make sure also the youtube url is not copyrighted, sometimes some youtube url does not play in CEF.
