### ISSUE TITLE
Can not select

### ISSUE THREAD

**Issue by TamerWaves** [renzuzu/renzu_multicharacter#48]
Installed both multicharacter with and without spawn on qbcore server. The loading screen and locations work (video moves about the city), but I cannot select my character or new character slot. I click but nothing happens. TIA for any help

**Comment by renzuzu** [comment]
any errors in F8?

**Comment by TamerWaves** [comment]
> any errors in F8?

None

**Comment by renzuzu** [comment]
probably your folder name have -main or something.
name it to renzu_multicharacter

**Comment by TamerWaves** [comment]
> 

Thanks so much, that was it. Love your work, keep it up! Very nice!
