### ISSUE TITLE
Per player amount of slots [QB]

### ISSUE THREAD

**Issue by Flexiboi** [renzuzu/renzu_multicharacter#49]
Hi

Is there a way to allow certain player to have more slots than others?
Using qb framework

Thanks!

**Comment by Flexiboi** [comment]
> /updatecharslots ID TOTALSLOT

TYSM!

Now an other problem I have it that character isnt loading when selecting it but does load when selected after i manualy restart the script in game.

**Comment by renzuzu** [comment]
need more info, i dont have issue in QBcore right now, using latest version

**Comment by Flexiboi** [comment]
So I start the resource in an other cfg file after qb-core is launched and most of the time when you join and select your character. It doesnt show / the character goes invincible.

But when i load in and restart the script the character loads in fine.

Could this be the order of starting the script on start?

And yes I run the latest QB 😄 
Thanks

**Comment by renzuzu** [comment]
yes order is important
if your using fivem-appearance, illenium, qb-clothing
make that is loaded before this resource
