### ISSUE TITLE
Create Character

### ISSUE THREAD

**Issue by FilipeCuco** [renzuzu/renzu_multicharacter#5]
https://streamable.com/a2x50y
if you create a character for the first time and then do /relog to create another character, the first character's information is in all the fields

**Comment by renzuzu** [comment]
how you did manage to fix your last issue? congrats

**Comment by FilipeCuco** [comment]
> how you did manage to fix your last issue? congrats

I don't know, I just downloaded the latest version of esx again and it worked

**Comment by renzuzu** [comment]
oh, next time use tx admin recipe , its more easy and they auto installed everything including sqls

**Comment by FilipeCuco** [comment]
![image](https://user-images.githubusercontent.com/116587926/204582427-06dbe8df-5555-4d32-b906-73e65ea71a40.png)
is this normal?

**Comment by renzuzu** [comment]
when you restart or keep relogin, this is could happen.

as gta limits the pedshots creation each session.

i will implement a cache system later on to prevent this

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_multicharacter/commit/0ba1a94dc25de3b226f4b5caccc479b6dde83786

**Comment by FilipeCuco** [comment]
design bug 
![image](https://user-images.githubusercontent.com/116587926/204669036-794487b4-69a7-4d97-b11d-e295f94aeda0.png)
