### ISSUE TITLE
Allows players to delete their characters

### ISSUE THREAD

**Issue by xXJay809Xx** [renzuzu/renzu_multicharacter#6]
-- Allows players to delete their characters
Config.CanDelete = false 

i set it to false and still let me delete the characters

**Comment by xXJay809Xx** [comment]
is another bug with renzu_multicharacter it making the server sound like it raining and you re running in water but you cant see no rain in the server

**Comment by renzuzu** [comment]
this is fixed in lastest commit, there is no interfering with rain intensity
